### ISSUE TITLE
Invalid/Outdated App Flags in Debug/Release Configs

### ISSUE THREAD

**Issue by Zagrophyte** [hedger/flipperzero-sesproject#2]
I had an issue where the Infrared app was missing, so I took the whole list and compared it against the applications.mk and found a few more discrepancies. Some of them may be intended like the extras, but the typos and other items will need some adjusting.

App vs Debug Config
![image](https://user-images.githubusercontent.com/6778687/166641211-99032d10-f3a1-4653-b735-1f2c2043152b.png)

App vs Release Config
![image](https://user-images.githubusercontent.com/6778687/166641295-a1523975-c42b-4d09-9757-06abb38c48d9.png)

**Comment by hedger** [comment]
Thank you. Merged and revised them.
